import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Providers from "./provider";
import { Session } from "./session";
import NavBar from "../components/headers/NavBar";
import Footer from "../components/Footer/Footer";
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Joebryan-Mall",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <Providers>
        <Session>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased text-slate-700   `}
          >
            <NavBar />
            <Toaster richColors position="top-right" />
            <main className="min-h-[100vh] w-full overflow-x-auto scrollbar-hide">
              {children}
            </main>
            <Footer />
          </body>
        </Session>
      </Providers>
    </html>
  );
}
